#!/usr/bin/python3
"""
test file
"""

import unittest
from models.rectangle import Rectangle

class TestRectangle(unittest.TestCase):
    """
        test cases for Rectangle class
    """

    def test_x(self):
        """test for the x variable on rectangle"""
        obj = Rectangle(width=5, height=10, x=36)
        self.assertEqual(obj.x, 36)
        with self.assertRaises(TypeError):
            obj.x = [1, "3"]
        with self.assertRaises(ValueError):
            obj.x = -9

    def test_y(self):
        """test for the y variable on rectangle"""
        obj = Rectangle(width=5, height=10, y=36)
        self.assertEqual(obj.y, 36)
        with self.assertRaises(TypeError):
            obj.y = [1, "4"]
        with self.assertRaises(ValueError):
            obj.y = -8

    def test_width(self):
        """test for the width variable on rectangle"""
        obj = Rectangle(width=36, height=5)
        self.assertEqual(obj.width, 36)
        with self.assertRaises(TypeError):
            obj.width = [1, "5"]
        with self.assertRaises(ValueError):
            obj.width = -6

    def test_height(self):
        """test for the height variable on rectangle"""
        obj = Rectangle(width=5, height=35)
        self.assertEqual(obj.height, 35)
        with self.assertRaises(TypeError):
            obj.height = [1, "10"]
        with self.assertRaises(ValueError):
            obj.height = -4

if __name__ == "__main__":
    unittest.main()
